sudo: required

services:
  - docker
script:
  - docker build -t BIDGroup/UOJ-Edu-Image install/bundle
  - docker images
  - docker run --name uoj -p 80:80 -p 3690:3690 --cap-add SYS_PTRACE BIDGroup/UOJ-Edu-Image
  - docker ps -a
  - wget http://127.0.0.1/
