sudo: required

services:
  - docker
script:
  - cd install/bundle
  - docker build -t bidgroup/uoj-edu-image .
  - docker images
  - docker run --name uoj -p 80:80 -p 3690:3690 --cap-add SYS_PTRACE bidgroup/uoj-edu-image
